/**
 * Organizer console icons — Heroicons 2 outline via react-icons.
 * One family for chrome, studio, dashboard, check-in, and finance.
 * Keep lucide Loader2 for spinners only.
 */
export type { IconType as OrgIconType } from "react-icons";

export {
  HiOutlineSquares2X2 as IconDashboard,
  HiOutlineCalendarDays as IconCalendar,
  HiOutlineQrCode as IconQr,
  HiOutlineBanknotes as IconBanknotes,
  HiOutlineCog6Tooth as IconSettings,
  HiOutlineArrowRightOnRectangle as IconLogout,
  HiOutlineUsers as IconUsers,
  HiOutlineWallet as IconWallet,
  HiOutlinePlus as IconPlus,
  HiOutlineArrowRight as IconArrowRight,
  HiOutlineArrowLeft as IconArrowLeft,
  HiOutlineChevronRight as IconChevronRight,
  HiOutlineChevronLeft as IconChevronLeft,
  HiOutlineChevronDown as IconChevronDown,
  HiOutlineExclamationTriangle as IconAlert,
  HiOutlineArrowPath as IconRefresh,
  HiOutlineKey as IconKey,
  HiOutlineXMark as IconClose,
  HiOutlineTicket as IconTicket,
  HiOutlineClipboardDocumentList as IconClipboard,
  HiOutlineSquare2Stack as IconCopy,
  HiOutlineMicrophone as IconMic,
  HiOutlinePhoto as IconPhoto,
  HiOutlinePlayCircle as IconWheel,
  HiOutlineLink as IconLink,
  HiOutlineEllipsisVertical as IconMore,
  HiOutlineTrash as IconTrash,
  HiOutlineArrowTopRightOnSquare as IconExternal,
  HiOutlineClock as IconClock,
  HiOutlineMapPin as IconMapPin,
  HiOutlineGlobeAlt as IconGlobe,
  HiOutlineWifi as IconWifi,
  HiOutlineSun as IconSun,
  HiOutlineMoon as IconMoon,
  HiOutlineComputerDesktop as IconMonitor,
  HiOutlineCamera as IconCamera,
  HiOutlineVideoCameraSlash as IconCameraOff,
  HiOutlineCheckCircle as IconCheckCircle,
  HiOutlineXCircle as IconXCircle,
  HiOutlineCheck as IconCheck,
  HiOutlineLockClosed as IconLock,
  HiOutlineCurrencyDollar as IconDollar,
  HiOutlineMagnifyingGlass as IconSearch,
  HiOutlineCheckBadge as IconLogoMark,
  HiOutlineCommandLine as IconKeyboard,
  HiOutlineSignalSlash as IconOffline,
  HiOutlineDocumentText as IconFileText,
  HiOutlineEye as IconEye,
  HiOutlineArrowTrendingUp as IconTrending,
  HiOutlineStar as IconStar,
  HiOutlineUserPlus as IconUserPlus,
  HiOutlinePencilSquare as IconPencil,
  HiOutlineBars3 as IconGrip,
  HiOutlineMegaphone as IconMegaphone,
  HiOutlineCube as IconPackage,
  HiOutlinePhone as IconPhone,
  HiOutlineChatBubbleLeftRight as IconChat,
  HiOutlineArrowUpTray as IconUpload,
  HiOutlineArrowDownTray as IconDownload,
  HiOutlineSparkles as IconSparkles,
  HiOutlineBolt as IconBolt,
  HiOutlineTrophy as IconTrophy,
  HiOutlineMinus as IconMinus,
  HiOutlineDocumentCheck as IconSave,
  HiOutlineRectangleStack as IconLibrary,
  HiOutlineArrowsPointingOut as IconMove,
  HiOutlineMagnifyingGlassPlus as IconZoomIn,
} from "react-icons/hi2";
